apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
resources:
  - namespace.yaml
helmCharts:
  - name: harbor
    repo: https://helm.goharbor.io
    releaseName: harbor
    namespace: harbor
    version: 1.15.0
    valuesFile: values.yaml
    includeCRDs: true
