apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb
resources:
  - namespace.yaml
  - ip-pool.yaml
  - advertisement.yaml
helmCharts:
  - name: metallb
    repo: https://metallb.github.io/metallb
    releaseName: metallb
    namespace: metallb
    version: 0.14.8
    valuesFile: values.yaml
    includeCRDs: true
